import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalStateProvider } from "@/context/GlobalState";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Ripple.ai",
  description: "Generated by Tres Phillips",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalStateProvider>{children}</GlobalStateProvider>
      </body>
    </html>
  );
}
